version: "3.8"

services:
  always-on:
    container_name: Discord-AlwaysOn
    build: ./always-on-service
    ports:
      - "4100:8080"
  cron-mess:
    container_name: Discord-CronMess
    build: ./cron-mess-service
    ports:
      - "4101:8080"
  music-bot:
    container_name: Discord-MusicBot
    build: ./music-bot-service
    ports:
      - "4102:8080"