version: "3.8"

services:
  always-on:
    container_name: always-on
    build: ./always-on-service
    ports:
      - "8184:8080"
  cron-mess:
    container_name: cron-mess
    build: ./cron-mess-service
    ports:
      - "8183:8080"
  music-bot:
    container_name: music-bot
    build: ./music-bot-service
    ports:
      - "8182:8080"